name: test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Test:
    strategy:
      matrix:
        lua-version: ["5.4", "5.3", "5.2", "5.1", "luajit"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"] # Ensure all desired OS are listed
        include:
          - os: "macos-latest"
            lua-version: "5.4"
          - os: "windows-latest"
            lua-version: "luajit"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua-version }}

      - uses: hishamhm/gh-actions-luarocks@master

      - name: Install libcurl
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libcurl4-openssl-dev
          elif [ "${{ runner.os }}" = "macOS" ]; then
            brew install curl
          elif [ "${{ runner.os }}" = "Windows" ]; then
            choco install curl
          fi

      - name: Build
        run: |
          luarocks make

      - name: Test
        run: |
          luarocks lint easy-http-dev-1.rockspec
          luarocks test
